apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: suraj
  labels:
    project: suraj
    component: db
    env: dev

spec:
  selector:
    matchLabels:
      project: suraj
      component: db
      env: dev
  serviceName: mysql
  replicas: 3
  template:
    metadata:
      labels:
        project: suraj
        component: db
        env: dev
    spec:
      containers:
      - name: mysql
        image:
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "suraj-sc"
      resources:
        requests:
          storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: suraj

spec:
  clusterIP: None
  selector:
    project: suraj
    component: db
    env: dev
  ports:
  - name: mysql
    protocol: TCP
    port: 3306 
    targetPort: 3306 

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # keep true in double quotes
  MYSQL_DATABASE: "cities"
  MYSQL_USER: "shipping"
  MYSQL_PASSWORD: "RoboShop@1"
